import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato, Roboto_Mono } from "next/font/google";

import "./globals.css";
import Navbar from "../components/navbar"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const roboto_Mono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} ${roboto_Mono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       {/* <Navbar /> */}
        {children}
        
        </body>
    </html>
  );
}
